{
  "hash": "29fe3c3eeb35ba99830e83d6f6b12a01",
  "result": {
    "markdown": "---\ntitle: \"Objective 4\"\n---\n\n\n## 4 Communicating results\n\nCourse Objective:\n\n> Communicate the results of statistical models to a general audience\n\n\n::: {.cell}\n\n:::\n\n\n## 4.1 Introduction\n\nTo communicate the results of a statistical model to a non-technical or a general audience, It is vital to simplify the results and generate easy to understand summary and data visualization. It is crucial to keep the message clear, concise, and easy to understand. As a rule of thumb, I've found that below steps works well:\n\n1.  State the purpose: By clearly stating the objective of the analysis and key questions(s) to answer, we can help the target audience understand the context and importance of finding.\n\n2.  Simple language: Always avoid complex technical jargon and statistical terminologies. We should use plain language to convey the findings.\n\n3.  Summarize findings: Clearly state the results of the analysis, emphasizing important and interesting insights.\n\n4.  Visualize data: Using graphs or other similar visual aids can help reach message to audience. It make information readily available and easier to digest.\n\n5.  Show limitations: Understand and acknowledge any limitations or uncertainties associated with the analysis, and provide context on how they might affect the results.\n\n## 4.2 Example\n\nTo illustrate, I will use the popular `mtcars` dataset that ships with base R. This dataset contains data about various car models that we can use to perform a simple linear regression. To predict the miles per gallon (mpg) based on the car's weight (wt) and horsepower (hp), I will use the `lm()` function.\n\nBelow is an example on how to communicate the results to a general audience:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the necessary libraries\nlibrary(ggplot2)\n\n# Load the data\ndata(mtcars)\n\n# Fit the linear model\nmodel <- lm(mpg ~ wt + hp, data = mtcars)\n```\n:::\n\n\n### 4.2.1 Report\n\nI would like to share the results of a linear regression analysis we conducted using the `mtcars` dataset. Our primary goal was to understand how a car's weight and horsepower affect its fuel efficiency, measured in miles per gallon.\n\nTo achieve this objective, we fitted a linear regression model that uses weight and horsepower as independent variables to predict miles per gallon. Below is a summary of our findings:\n\n1.  Weight: Our findings suggest that there is a negative relationship between a car's weight and its fuel efficiency. This means that as a car's weight increases, its miles per gallon tends to decrease. Heavier cars generally consume more fuel than lighter ones.\n2.  Horsepower: We found that horsepower also has a negative relationship with fuel efficiency. As horsepower increases, miles per gallon decreases. This suggests that cars with higher horsepower generally have lower fuel efficiency.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display the summary of the model\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mpg ~ wt + hp, data = mtcars)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.941 -1.600 -0.182  1.050  5.854 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 37.22727    1.59879  23.285  < 2e-16 ***\nwt          -3.87783    0.63273  -6.129 1.12e-06 ***\nhp          -0.03177    0.00903  -3.519  0.00145 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.593 on 29 degrees of freedom\nMultiple R-squared:  0.8268,\tAdjusted R-squared:  0.8148 \nF-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12\n```\n:::\n:::\n\n\nOur linear regression analysis revealed the following key statistical results:\n\n1.  Coefficients: The model's coefficients indicate the average change in the dependent variable (mpg) for a one-unit change in the independent variables (wt and hp), holding all other variables constant. Our coefficients are:\n\n    -   Intercept: 37.2273\n    -   Weight (wt): -3.8778\n    -   Horsepower (hp): -0.0318\n\n    This means that, on average, an increase in weight by 1,000 lbs is associated with a decrease in mpg by 3.8778 units, and an increase in horsepower by 1 unit is associated with a decrease in mpg by 0.0318 units.\n\n2.  Multiple R-squared: This statistic represents the proportion of variation in the dependent variable (mpg) that is explained by the independent variables (wt and hp). Our Multiple R-squared value is 0.8268, meaning that our model explains 82.68% of the variation in mpg.\n\n3.  F-statistic: The F-statistic is used to test the overall significance of the model, i.e., whether the independent variables (wt and hp) have a significant impact on the dependent variable (mpg). Our F-statistic is 70.91, with a very low p-value (\\< 0.0001). This indicates that our model is statistically significant, and the independent variables have a meaningful impact on mpg.\n\n4.  Residual standard error: This statistic measures the average deviation of the observed values from the predicted values. Our residual standard error is 2.639, meaning that, on average, our model's predictions deviate from the actual mpg values by 2.639 units.\n\nTo help visualize these relationships, we have included a visualization that demonstrates the actual data points, along with the fitted regression lines for each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = wt, y = mpg, color = hp)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(\n    title = \"Miles per Gallon vs. Weight and Horsepower\",\n    x = \"Weight (1000 lbs)\",\n    y = \"Miles per Gallon\",\n    color = \"Horsepower\"\n  )\n```\n\n::: {.cell-output-display}\n![](objective-4_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nAs shown in the graph above, there is a clear negative correlation between weight, horsepower, and miles per gallon. The data indicate that cars with lower weight and horsepower generally have better fuel efficiency.\n\nIn summary, our analysis reveals that both weight and horsepower significantly influence a car's fuel efficiency. This information can be helpful for consumers when considering which car to purchase, as well as for car manufacturers looking to design more fuel-efficient vehicles.\n",
    "supporting": [
      "objective-4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}